

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        image: ${DOCKER_IMAGE_NAME}
        container_name: ${$DOCKER_PHP_CONTAINER_NAME}
        build: .docker/php
        ports:
            - 5173:5173
        network: ${DOCKER_NETWORK_NAME}
        

