version: '3'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: jenkings_test_php
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: jenkings_test_nginx
        image: nginx
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .docker/nginx/certs:/etc/nginx/ssl
        depends_on:
            - php

    ####################################################################################################
    # DATABASE (MySQL)
    # docker exec -it jenkings_test_mysql bash -c "mysql -u root -proot"
    ####################################################################################################
    jenkings_test_db:
        container_name: jenkings_test_mysql
        image: mysql:8.0
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jenkings_test_db_name
            MYSQL_USER: jenkings_test_db_user
            MYSQL_PASSWORD: jenkings_test_db_pass

