version: '3'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: jenkins_php
        build: .docker/php
        ports:
            - 5173:5173
        

   
